### PR TITLE
oidnv2.2.2

### PR DESCRIPTION
**Pull request by float3**
idk if I'm missing anything, i tried it on my path tracer and tried your examples and and it seems to work just fine

### CODE REVIEW

**Comment by float3** [comment]
before this is merged you should probably publish the 2.1.0 crate to crates.io, generally if you're short on time I'm also willing to become a maintainer of this crate

**Comment by Twinklebear** [comment]
Thanks @float3 , this looks good! I think the only thing we need to update is the download URL for the windows build for the CI runner, looking at the releases page: https://github.com/OpenImageDenoise/oidn/releases/tag/v2.2.2 it should be 
```
oidn-${env:OIDN_VERSION}.x64.windows.zip
```
instead of
```
oidn-${env:OIDN_VERSION}.x64.vc14.windows.zip
```

These days I should have some time to do basic stuff, but the crate has mainly been in maintence/minimal mode for me since I've been working on different side projects lately. I should have time to review PRs and help out with some stuff, but lets see. I'm open to adding folks though if there's interest in adding more to the crate. GPU denoise support would be a big but cool feature, since OIDN supports it now.

**Comment by float3** [comment]
maybe to future proof we could just curl the specific release and check the output for the download url? I guess implementing that in bash commands would be just as fragile as hardcoding file names though

**Comment by float3** [comment]
will adjust it tomorrow

**Comment by float3** [comment]
i wanna look into gpu denoise support!

**Comment by float3** [comment]
closed https://github.com/Twinklebear/oidn-rs/issues/24 since relevant conversation should continue here

**Pull request merged**
